### Numpy

In [1]:
import numpy as np

In [2]:
x=np.array([10,20,30,40])

In [3]:
x

array([10, 20, 30, 40])

In [4]:
type(x)

numpy.ndarray

In [6]:
y=np.array([[10,20,30],[40,50,60]])

In [7]:
y

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
z=np.zeros((1,6))

In [9]:
z

array([[0., 0., 0., 0., 0., 0.]])

In [10]:
z=np.zeros((5,5))

In [11]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
z=np.ones((5,5))

In [13]:
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
s=np.full((3,3),5)

In [15]:
s

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [16]:
a=np.arange(100,150)

In [17]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [18]:
a=np.arange(100,200,5)

In [19]:
a

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [20]:
a=np.random.randint(1,100)

In [21]:
a

25

In [25]:
a=np.random.randint(1,100,10)

In [26]:
a

array([52, 83, 85, 96, 65, 16, 30, 12, 68, 19])

In [27]:
n1=np.array([[1,2,3,4],[5,6,7,8]])

In [28]:
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
n1.shape

(2, 4)

In [32]:
n1.shape=(4,2)

n1

In [33]:
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
n1=np.array([10,20,30])

In [35]:
n2=np.array([40,50,60])

In [36]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [37]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [39]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [40]:
np.intersect1d(n1,n2)

array([], dtype=int32)

In [41]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [43]:
np.setdiff1d(n2,n1)

array([40, 50, 60])

In [44]:
np.sum([n1,n2])

210

In [45]:
np.sum([n1,n2],axis=0)

array([50, 70, 90])

In [46]:
np.sum([n1,n2],axis=1)

array([ 60, 150])

In [47]:
n1=n1+1

In [48]:
n1

array([11, 21, 31])

In [49]:
n1=n1*2

In [50]:
n1

array([22, 42, 62])

In [51]:
n1=n1-5

In [52]:
n1

array([17, 37, 57])

In [53]:
n1=np.mean(n1)

In [54]:
n1

37.0

In [55]:
n2=np.mean(n2)

In [56]:
n2

50.0

In [57]:
np.std(n1)

0.0

In [58]:
np.median(n1)

37.0

In [59]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
b[0]

array([1, 2, 3])

In [61]:
b[1]

array([4, 5, 6])

In [62]:
b[2]

array([7, 8, 9])

In [63]:
b[:,1]

array([2, 5, 8])

In [64]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
b[1,:]

array([4, 5, 6])

In [66]:
b.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [67]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
b.dot(n1)

array([[ 37.,  74., 111.],
       [148., 185., 222.],
       [259., 296., 333.]])

In [70]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.save('my_numpy',n1)

In [74]:
c=np.load('my_numpy.npy')

In [75]:
c

array(37.)